export const ALL_BLOGS_SUCCESS = 'ALL_BLOGS_SUCCESS'
export const ALL_BLOGS_FAIL = 'ALL_BLOGS_FAIL'

export const BLOGS_DETAILS_SUCCESS = 'BLOG_DETAILS_SUCCESS'
export const BLOGS_DETAILS_FAIL = 'BLOG_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const REVIEW_AVAILABILITY_REQUEST = 'REVIEW_AVAILABILITY_REQUEST'
export const REVIEW_AVAILABILITY_SUCCESS = 'REVIEW_AVAILABILITY_SUCCESS'
export const REVIEW_AVAILABILITY_FAIL = 'REVIEW_AVAILABILITY_FAIL'

export const ADMIN_BLOGS_REQUEST = 'ADMIN_BLOGS_REQUEST'
export const ADMIN_BLOGS_SUCCESS = 'ADMIN_BLOGS_SUCCESS'
export const ADMIN_BLOGS_FAIL = 'ADMIN_BLOGS_FAIL'

export const NEW_BLOG_REQUEST = 'NEW_BLOG_REQUEST'
export const NEW_BLOG_SUCCESS = 'NEW_BLOG_SUCCESS'
export const NEW_BLOG_RESET = 'NEW_BLOG_RESET'
export const NEW_BLOG_FAIL = 'NEW_BLOG_FAIL'

export const UPDATE_BLOG_REQUEST = 'UPDATE_BLOG_REQUEST'
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS'
export const UPDATE_BLOG_RESET = 'UPDATE_BLOG_RESET'
export const UPDATE_BLOG_FAIL = 'UPDATE_BLOG_FAIL'

export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST'
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS'
export const DELETE_BLOG_RESET = 'DELETE_BLOG_RESET'
export const DELETE_BLOG_FAIL = 'DELETE_BLOG_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'